# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 811371bc318766667f4f0d5c0dc8468ab91048932e1b929ad54c21524aff065f55be45a8ac6ca4edbe3dc38801430cdd396cdc6198b85f73025d9347ca0d8ac4

test:
  secret_key_base: 2aa2d62ffe94727991cae1ab94da5d22d90a3b2f7082bd85629a9d226a246e213b8a56a21769112ef34abdc08254770a8a5dc70a058e936126b2a8772468f28f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
